#
# Static definition of "discoverable-client" as "staticclient"
#
# This file provides static API service definition in YAML format.
# It is loaded by the Discovery Service during its startup.
#
services:
    - serviceId: localtomcat
      catalogUiTileId: mystatic
      title: Statically Defined Tomcat
      description: Local Tomcat server with examples
      instanceBaseUrls:  # list of base URLs for each instance
        - https://localhost:8443
      homePageRelativeUrl: examples
      routes:
        - gatewayUrl: /
          serviceRelativeUrl: /
        - gatewayUrl: ws/v3
          serviceRelativeUrl: examples/websocket/echoAnnotation  # DOES NOT WORK
        - gatewayUrl: ws/v2                       # wss://localhost:10010/localtomcat/ws/v2/echoAnnotation  -->
          serviceRelativeUrl: examples/websocket  # wss://localhost:8443/examples/websocket/echoAnnotation
        - gatewayUrl: ws/v1
          serviceRelativeUrl: examples
        - gatewayUrl: ws/v0
          serviceRelativeUrl: /
      # List of APIs provided by the service (currently only one is supported):
      apiInfo:
        - apiId: jakub.localtomcat
          gatewayUrl: examples

# List of tiles that can be used by services defined in the YAML file:
catalogUiTiles:
    mystatic:
        title: My sample Services
        description: Local test Services

# Tomcat server.xml
#  <Connector port="8443" protocol="org.apache.coyote.http11.Http11NioProtocol" maxThreads="150" SSLEnabled="true">
#   <SSLHostConfig>
#    <Certificate certificateKeyFile="C:/Users/Jakub/IdeaProjects/APIML/keystore/localhost/localhost.keystore.key"
#                 certificateFile="C:/Users/Jakub/IdeaProjects/APIML/keystore/localhost/localhost.keystore.cer"
#                 type="RSA" />
#   </SSLHostConfig>
#  </Connector>
